name: MeshMeld
title: MeshMeld, Melding Technology 
tagline: Melding Technology
location: Vancouver, BC
twitter: https://twitter.com/meshmeld
githublink: https://github.com/infamy
markdown: redcarpet
pygments: false
paginate: 5
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]